--- 
title: "Golden Cross : An Interactive & Insightful Study on Stock Market"
author: "Vipul H Harihar, Zhaoyu Wu, Zhirui Yang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

**Golden Cross: EDAV Final Project Assignment**

Golden Cross Project is using relevant stock market data for interactive study and conclusions. In this project, the reader might feel free to explore the study performed at subsequent levels to understand that how we came to find the golden cross and the various insights which are accessible in the upcoming chapters. The project team comprises:Vipul H Harihar, Zhaoyu Wu and Zhirui Yang 
We have have put all our classroom teachings and honest hardwork so as to make this project to reach its conclusion. We hope the user enjoys it as much as we did building and developing it. 

***Sit for a while because this Project will embrace your knowledge with the unknown of Stock Markets and Golden Cross which is majestic in itself!***

### Introduction

There is a wide variety of ways to generate profits in stock markets. Almost everyone knows how to make a profit from a trade: buy low, sell high. But the true million-dollar questions here are tricky: how do you know the stock price is low enough for you to buy? how do you know the price is high enough for you to sell? How do you determine the timing of the trade? The perfect solutions to these questions might not even exist or at least not widely known, otherwise, most of the people would become millionaires. However, some strategies take the advantage of the power of statistics and data visualization. These strategies do not necessarily guarantee the profits, but they surely do point the direction to the profits based on statistics and probability. One of these strategies is Golden Cross. But before we get into that, let's review some basics:

## Why ‘Stocks’ ? What is ‘Stock Exchange’? 
A stock or the term share is usually used in representing a company's equity. We may understand it as a financial instrument that assists in showing ownership in a corporation or a company and it represents a proportionate claim on its assets (what it owns) and earnings (what it generates in profits). When we think of the term share stock exchanges, it is the secondary market, where existing owners of shares can transact these shares of their equities with potential buyers. It is important to comprehend that the corporations on stock markets do not buy and sell their own shares on a regular basis (companies may engage in stock buybacks or issue new shares, but these are not day-to-day operations and often occur outside of the framework of an exchange). So we may sum it as whenever you buy a share of stock on the stock market, you are not buying the stock directly from the company, you are buying it from another existing shareholder. Likewise, when you want to sell the shares you own , they are not sold to the company—rather you sell them to some other investors.

Project Problem Statement There are numerous people in the market who want to invest in the stock market are way too afraid to put their life’s savings at stake. Many people pour their life savings and dump their 401K (contribution retirement plan) into the stock and option market. They perform various strategies and financial maneuvers, hoping to gain massive profits but generally end up losing most of their investments or still having underperformance in the general market. Thus, our team started thinking if there is an investing strategy that can consistently beat the index fund return.

### What is Golden Cross and how does it work? 

A golden cross is a chart pattern in which a relatively short-term moving average crosses above a long-term moving average. The golden cross is a bullish breakout pattern formed from a crossover involving a security's short-term moving average (such as the 15-day moving average) breaking above its long-term moving average (such as the 50-day moving average) or resistance level.

There are three stages to a golden cross. The first stage requires that a downtrend eventually bottoms out as selling is depleted. In the second stage, the short term moving average cross the long term moving average, triggering a breakout and confirmation of trend reversal. The moving averages act as support levels on pullbacks until they crossover back down at which point a death cross may form. The death cross is the opposite of the golden cross as the shorter moving average forms a crossover down through the longer moving average.

With a bellwether index, the motto «A rising tide lifts all boats» applies when a golden cross forms as the buying resonates throughout the index components and sectors. Day traders commonly use smaller time periods like the 5-period and 15-period moving averages to trade intra-day golden cross breakouts. The larger the chart time frame, the stronger and lasting the golden cross breakout tends to be.


### The Difference Between a Golden Cross and a Death Cross

A golden cross indicates a long-term bull market going forward, while a death cross signals a long-term bear market. The golden cross occurs when a short-term moving average crosses over a major long-term moving average to the upside and is interpreted by analysts and traders as signaling a definitive upward turn in a market.

**Limitations of Using the Golden Cross**

Many times, an observed golden cross produces a false signal. Despite its apparent predictive power in forecasting prior large bull markets, golden crosses also do regularly fail to manifest. Therefore, a golden cross should always be confirmed with other signals and indicators before putting on a trade.

**What Does a Golden Cross Indicate?**

A golden cross suggests a long-term bull market going forward.

Are Golden Crosses Reliable Indicators?

Traders often use a golden cross as confirmation of a trend or signal in combination with other indicators.

**Outline of our Work Done in Project**

• A financial study on the stock market published last year raised an intriguing theory 

• Golden Cross and it’s capabilities EDAV Final Project Assignment 4 

• Data Cleaning and Exploration

• Report writing and visuals finalization 


**Allocation of Duties**

Zhaoyu Wu chose the topic of the project and worked on data visualization and text composition. He created interactive candlestick plots and other static data visualization and interpretations. Vipul Harihar worked on GitHub script managing, book rendering, and text composition. He also worked on the D3 interactive plots. Zhirui Yang worked on data cleaning and preprocessing.

##  Goal of our Golden Cross Project: We built a project on these questions:

Data Investigation and checking if ‘Golden Cross’ exists by analyzing the trends in the past 10 years data?

• Examination from a pure data perspective, using the visualization techniques to demonstrate profit generated by Golden Cross investment method.

• What are some of the factors that influence the magnitude of this dislocation?

• Generate buy and sell signals according to the Gold Cross

• Calculation of the golden cross Data Source and its availability:

